/*******************************************************************************
*   Neufund
*   (c) 2016 Neufund
*   based on example from:
*   Ledger Blue
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

#include "os.h"
#include "cx.h"

#include "os_io_seproxyhal.h"
#include "string.h"

// execution environment
unsigned char G_io_seproxyhal_spi_buffer[IO_SEPROXYHAL_BUFFER_SIZE_B]; // io events like key presses go here, that's probably an EXTERN somewhere..
// IO_SEPROXYHAL_BUFFER_SIZE_B declared in makefile
// G_io_apdu_buffer is provided externally, a piece of shared mem where you write and read messages
ux_state_t ux; // this is used in every function that starts with io_ probably some autogenerated code

// client message elements
#define CLA 0x80 // magic number
// INS_GET_KEY command layout
// CLA INS_GET_KEY KEY_PART_MASK LEN(UINT) PATH_DATA...
// KEY_PART_MASK says which key elements should be returned, if part is not requested a string of 0x0 is returned
// LEN says how many UINT path elements are there
#define INS_GET_KEY 0x04 // get public key
#define INS_GET_KEY_KEY_PART_MASK_IDX 2
#define INS_GET_KEY_PATH_LEN_IDX 3
#define INS_GET_KEY_PATH_DATA_IDX 4
// bits for key parts
#define KEY_PART_MASK_PRIV 1
#define KEY_PART_MASK_PUB 2
#define KEY_PART_MASK_CHAINCODE 4

// user interface stuff
// check if device has given feature
#define DEVICE_HAS_FEATURE(f) os_seph_features() & f
unsigned int current_text_pos; // parsing cursor in the text to display
unsigned int text_y;           // current location of the displayed text
// forward declarations
void ui_idle(void); // show idle UI
void ui_text(void); // show confirm text UI

// UI currently displayed
enum UI_STATE { UI_IDLE, UI_TEXT, UI_APPROVAL };
enum UI_STATE uiState;

unsigned int io_seproxyhal_touch_exit(bagl_element_t *e);
unsigned int io_seproxyhal_touch_approve(bagl_element_t *e);
unsigned int io_seproxyhal_touch_deny(bagl_element_t *e);

#define MAX_CHARS_PER_LINE 49
#define DEFAULT_FONT BAGL_FONT_OPEN_SANS_LIGHT_13px | BAGL_FONT_ALIGNMENT_LEFT
#define TEXT_HEIGHT 15
#define TEXT_SPACE 4

char lineBuffer[50];
char key_part_mask;

#include "ui_definitions.h"

unsigned int io_seproxyhal_touch_exit(bagl_element_t *e) {
    // Go back to the dashboard
    os_sched_exit(0);
    return 0; // do not redraw the widget
}

typedef struct  extended_pub_key_t {
    cx_ecfp_public_key_t pubKey;
    unsigned char chainCode[32];
} extended_pub_key_t;

void derive(unsigned int * path, unsigned int pathLength, cx_ecfp_private_key_t * privateKey, extended_pub_key_t * rv_publicKey) {
    // derive bip32 node from master secret
    unsigned char privateKeyData[32];
    // unsigned int * path = DERIVATION_PATH; 10
    os_perso_derive_node_bip32(CX_CURVE_256K1, path, pathLength, privateKeyData, rv_publicKey->chainCode);
    cx_ecdsa_init_private_key(CX_CURVE_256K1, privateKeyData, 32, privateKey);
    cx_ecfp_generate_pair(CX_CURVE_256K1, &rv_publicKey->pubKey, privateKey, 1);
}

unsigned int io_seproxyhal_touch_approve(bagl_element_t *e) {
    unsigned int tx = 0;
    extended_pub_key_t ext_publicKey;
    cx_ecfp_private_key_t privateKey;
    // get which parts of key to return
    unsigned char key_part_mask = G_io_apdu_buffer[INS_GET_KEY_KEY_PART_MASK_IDX];
    // get path and path length (in segments), derive node
    uint32_t * dataBuffer = (uint32_t *)(G_io_apdu_buffer + INS_GET_KEY_PATH_DATA_IDX);
    // uncompressed pub key will be returned (x, y coordiates on a curve)
    derive(dataBuffer, G_io_apdu_buffer[INS_GET_KEY_PATH_LEN_IDX], &privateKey, &ext_publicKey);
    // move pub key to out buffer
    if(key_part_mask&KEY_PART_MASK_PUB)
        os_memmove(G_io_apdu_buffer, ext_publicKey.pubKey.W, 65);
    else
        os_memset(G_io_apdu_buffer, 0, 65);
    tx = 65;
    // move private key to out buffer
    if(key_part_mask&KEY_PART_MASK_PRIV)
        os_memmove(G_io_apdu_buffer + tx, privateKey.d, 32);
    else
        os_memset(G_io_apdu_buffer + tx, 0, 32);
    tx += 32;
    // move chaincode to out buffer
    if(key_part_mask&KEY_PART_MASK_CHAINCODE)
        os_memmove(G_io_apdu_buffer + tx, ext_publicKey.chainCode, 32);
    else
        os_memset(G_io_apdu_buffer + tx, 0, 32);
    tx += 32;
    G_io_apdu_buffer[tx++] = 0x90;
    G_io_apdu_buffer[tx++] = 0x00;
    // Send back the response, do not restart the event loop
    io_exchange(CHANNEL_APDU | IO_RETURN_AFTER_TX, tx);
    // Display back the original UX
    ui_idle();
    return 0; // do not redraw the widget
}

unsigned int io_seproxyhal_touch_deny(bagl_element_t *e) {
    G_io_apdu_buffer[0] = 0x69;
    G_io_apdu_buffer[1] = 0x85;
    // Send back the response, do not restart the event loop
    io_exchange(CHANNEL_APDU | IO_RETURN_AFTER_TX, 2);
    // Display back the original UX
    ui_idle();
    return 0; // do not redraw the widget
}

unsigned short io_exchange_al(unsigned char channel, unsigned short tx_len) {
    switch (channel & ~(IO_FLAGS)) {
    case CHANNEL_KEYBOARD:
        break;

    // multiplexed io exchange over a SPI channel and TLV encapsulated protocol
    case CHANNEL_SPI:
        if (tx_len) {
            io_seproxyhal_spi_send(G_io_apdu_buffer, tx_len);

            if (channel & IO_RESET_AFTER_REPLIED) {
                reset();
            }
            return 0; // nothing received from the master so far (it's a tx
                      // transaction)
        } else {
            return io_seproxyhal_spi_recv(G_io_apdu_buffer,
                                          sizeof(G_io_apdu_buffer), 0);
        }

    default:
        THROW(INVALID_PARAMETER);
    }
    return 0;
}

void app_main(void) {
    volatile unsigned int rx = 0;
    volatile unsigned int tx = 0;
    volatile unsigned int flags = 0;

    // DESIGN NOTE: the bootloader ignores the way APDU are fetched. The only
    // goal is to retrieve APDU.
    // When APDU are to be fetched from multiple IOs, like NFC+USB+BLE, make
    // sure the io_event is called with a
    // switch event, before the apdu is replied to the bootloader. This avoid
    // APDU injection faults.
    for (;;) {
        volatile unsigned short sw = 0;

        BEGIN_TRY {
            TRY {
                rx = tx;
                tx = 0; // ensure no race in catch_other if io_exchange throws
                        // an error
                rx = io_exchange(CHANNEL_APDU | flags, rx);
                flags = 0;

                // no apdu received, well, reset the session, and reset the
                // bootloader configuration
                if (rx == 0) {
                    THROW(0x6982);
                }

                if (G_io_apdu_buffer[0] != CLA) {
                    THROW(0x6E00);
                }

                switch (G_io_apdu_buffer[1]) {
                case INS_GET_KEY: {
                    // Wait for the UI to be completed
                    current_text_pos = 0;
                    text_y = 60;
                    // print path and wait for confirmation
                    unsigned int plen = G_io_apdu_buffer[INS_GET_KEY_PATH_LEN_IDX];
                    if ((plen < 0x01) || (plen > MAX_BIP32_PATH)) {
                        THROW(0x6a80);
                    }
                    char buf[bip32_path_buffer_size(plen)];
                    bip32_sprint_path(buf, (uint32_t *)(G_io_apdu_buffer + INS_GET_KEY_PATH_DATA_IDX), plen);
                    display_text_part(buf);
                    ui_text();

                    flags |= IO_ASYNCH_REPLY;
                } break;

                case 0xFF: // return to dashboard
                    goto return_to_dashboard;

                default:
                    THROW(0x6D00);
                    break;
                }
            }
            CATCH_OTHER(e) {
                switch (e & 0xF000) {
                case 0x6000:
                case 0x9000:
                    sw = e;
                    break;
                default:
                    sw = 0x6800 | (e & 0x7FF);
                    break;
                }
                // Unexpected exception => report
                G_io_apdu_buffer[tx] = sw >> 8;
                G_io_apdu_buffer[tx + 1] = sw;
                tx += 2;
            }
            FINALLY {
            }
        }
        END_TRY;
    }

return_to_dashboard:
    return;
}


unsigned char io_event(unsigned char channel) {
    // nothing done with the event, throw an error on the transport layer if
    // needed

    // can't have more than one tag in the reply, not supported yet.
    switch (G_io_seproxyhal_spi_buffer[0]) {
    case SEPROXYHAL_TAG_FINGER_EVENT:
        UX_FINGER_EVENT(G_io_seproxyhal_spi_buffer);
        break;

    case SEPROXYHAL_TAG_BUTTON_PUSH_EVENT: // for Nano S
        UX_BUTTON_PUSH_EVENT(G_io_seproxyhal_spi_buffer);
        break;

    case SEPROXYHAL_TAG_DISPLAY_PROCESSED_EVENT:
        UX_DISPLAYED_EVENT({});
        // firmware 1.2 below
        /*if (UX_DISPLAYED()) {
            } else {
                UX_DISPLAY_PROCESSED_EVENT();
            }*/
        break;

    case SEPROXYHAL_TAG_TICKER_EVENT:
        UX_REDISPLAY();
        break;

    // unknown events are acknowledged
    default:
        break;
    }

    // close the event if not done previously (by a display or whatever)
    if (!io_seproxyhal_spi_is_status_sent()) {
        io_seproxyhal_general_status();
    }

    // command has been processed, DO NOT reset the current APDU transport
    return 1;
}

__attribute__((section(".boot"))) int main(void) {
    // exit critical section
    __asm volatile("cpsie i");

    current_text_pos = 0;
    text_y = 60;
    uiState = UI_IDLE;

    // ensure exception will work as planned
    os_boot();

    UX_INIT();

    BEGIN_TRY {
        TRY {
            io_seproxyhal_init();

#ifdef LISTEN_BLE
            if (os_seph_features() &
                SEPROXYHAL_TAG_SESSION_START_EVENT_FEATURE_BLE) {
                BLE_power(0, NULL);
                // restart IOs
                BLE_power(1, NULL);
            }
#endif

            USB_power(0);
            USB_power(1);

            ui_idle();
            app_main();
        }
        CATCH_OTHER(e) {
        }
        FINALLY {
        }
    }
    END_TRY;
}
